server:
  port: 8981
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.35.133:3306/hospital?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ylfqw
    password: ylfqw
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 3000
      connection-test-query: SELECT 1
mvc:
  static-path-pattern: static/**
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.hospitalphoneservicebean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.example.hospitalphoneservice.mapper : debug



